/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#a1d0c4",
        surface: "#f4fbf7",
        "error-container": "#ffdad6",
        "outline-variant": "#bbcac5",
        "on-tertiary-fixed": "#3c0800",
        "on-primary-fixed-variant": "#005045",
        "on-primary-fixed": "#00201b",
        "on-surface": "#171d1b",
        "surface-container": "#e9efec",
        "surface-container-highest": "#dee4e1",
        "inverse-primary": "#57dbc3",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3c4946",
        "tertiary-fixed": "#ffdad2",
        "surface-bright": "#f4fbf7",
        "on-secondary-container": "#3e6b61",
        background: "#f4fbf7",
        primary: "#006b5c",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#bdece0",
        "surface-variant": "#dee4e1",
        "on-tertiary-container": "#5f1704",
        outline: "#6c7a76",
        "on-secondary-fixed-variant": "#214e45",
        "surface-tint": "#006b5c",
        "inverse-on-surface": "#ecf2ef",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        secondary: "#3a665d",
        "surface-container-high": "#e3eae6",
        "primary-fixed": "#77f8df",
        "on-background": "#171d1b",
        "on-secondary-fixed": "#00201b",
        "primary-fixed-dim": "#57dbc3",
        "on-tertiary-fixed-variant": "#7d2c18",
        "tertiary-container": "#e57b60",
        "on-error": "#ffffff",
        "secondary-container": "#bae9dd",
        error: "#ba1a1a",
        "surface-container-low": "#eff5f2",
        tertiary: "#9c432c",
        "inverse-surface": "#2b3230",
        "surface-dim": "#d5dbd8",
        "tertiary-fixed-dim": "#ffb4a2",
        "primary-container": "#03ac96",
        "on-primary-container": "#003830",
        "tertiary-dim": "#714c00",
        "secondary-dim": "#664f24",
        "error-dim": "#70030f",
        "primary-dim": "#005e52"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "space-2xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-3xl": "4rem",
        "space-xs": "0.5rem",
        "margin-mobile": "1rem",
        "space-2xl": "3rem",
        "touch-min": "3rem",
        "margin-desktop": "2.5rem"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Domine", "serif"],
        "headline-lg": ["Domine", "serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Domine", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Domine", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Domine", "serif"],
        headline: ["Domine", "serif"],
        display: ["Domine", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}